name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # اسم الفرع الرئيسي لديك (تأكد إذا كان main أو master)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20" # نسخة نود المستخدمة في مشروعك
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci # أو yarn install إذا كنت تستخدم yarn

      - name: Build with Next.js
        run: npm run build # سيقوم هذا الأمر بإنشاء مجلد out تلقائياً

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # مجلد المخرجات الثابتة لـ Next.js

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
